import { defineBank } from './types.js';

export const codingBank = defineBank('coding', [
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'What is a "bug" in a computer program?',
    options: [
      { id: 'a', text: 'A mistake that makes it behave wrongly' },
      { id: 'b', text: 'A type of computer' },
      { id: 'c', text: 'A kind of keyboard' },
      { id: 'd', text: 'A finished program' },
    ],
    correctOptionId: 'a',
  },
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'What do we call a step-by-step set of instructions for solving a problem?',
    options: [
      { id: 'a', text: 'A variable' },
      { id: 'b', text: 'An algorithm' },
      { id: 'c', text: 'A pixel' },
      { id: 'd', text: 'A browser' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'easy',
    type: 'true_false',
    prompt: 'A loop lets a program repeat the same instructions.',
    correct: true,
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What do we call a named box that stores a value in a program?',
    accepted: ['variable', 'a variable'],
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'How many bits are there in a byte?',
    accepted: ['8'],
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Which of these is a programming language?',
    options: [
      { id: 'a', text: 'HTTP' },
      { id: 'b', text: 'Python' },
      { id: 'c', text: 'USB' },
      { id: 'd', text: 'JPEG' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'What does an "if" statement do?',
    options: [
      { id: 'a', text: 'Repeats code forever' },
      { id: 'b', text: 'Stores a list of values' },
      { id: 'c', text: 'Runs code only when a condition is true' },
      { id: 'd', text: 'Prints text to the screen' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'medium',
    type: 'true_false',
    prompt: 'In most programming languages, the first item of a list is at index 1.',
    correct: false,
    explanation: 'Most languages count from zero, so the first item is at index 0.',
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What do we call a reusable block of code that you can call by name?',
    accepted: ['function', 'a function', 'method'],
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'In binary, what is the decimal value of 1010?',
    accepted: ['10'],
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'What does HTML stand for?',
    options: [
      { id: 'a', text: 'HyperText Markup Language' },
      { id: 'b', text: 'High Transfer Machine Language' },
      { id: 'c', text: 'Hyperlink Text Making Language' },
      { id: 'd', text: 'Home Tool Markup Language' },
    ],
    correctOptionId: 'a',
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'Which data structure follows "last in, first out"?',
    options: [
      { id: 'a', text: 'Queue' },
      { id: 'b', text: 'Stack' },
      { id: 'c', text: 'Tree' },
      { id: 'd', text: 'Graph' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'hard',
    type: 'true_false',
    prompt: 'A function that calls itself is described as recursive.',
    correct: true,
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What do we call the process of finding and fixing errors in code?',
    accepted: ['debugging', 'debug'],
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'How many different values can a single byte represent?',
    accepted: ['256'],
  },
]);
