import { defineBank } from './types.js';

export const englishBank = defineBank('english', [
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Which word is a noun?',
    options: [
      { id: 'a', text: 'Quickly' },
      { id: 'b', text: 'Mountain' },
      { id: 'c', text: 'Bright' },
      { id: 'd', text: 'Running' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'What is the plural of "child"?',
    options: [
      { id: 'a', text: 'Childs' },
      { id: 'b', text: 'Childes' },
      { id: 'c', text: 'Children' },
      { id: 'd', text: 'Childrens' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'easy',
    type: 'true_false',
    prompt: 'A sentence must always begin with a capital letter.',
    correct: true,
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the opposite of "ancient"?',
    accepted: ['modern', 'new', 'recent'],
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'Which punctuation mark ends a question?',
    accepted: ['question mark', '?'],
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Which sentence uses the apostrophe correctly?',
    options: [
      { id: 'a', text: 'The dog wagged it\u2019s tail.' },
      { id: 'b', text: 'The dogs\u2019 bowls were empty.' },
      { id: 'c', text: 'Three cat\u2019s sat on the wall.' },
      { id: 'd', text: 'Its\u2019 a sunny day.' },
    ],
    correctOptionId: 'b',
    explanation: 'A plural noun ending in s takes the apostrophe after the s.',
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'What figure of speech is "the wind whispered through the trees"?',
    options: [
      { id: 'a', text: 'Simile' },
      { id: 'b', text: 'Personification' },
      { id: 'c', text: 'Hyperbole' },
      { id: 'd', text: 'Alliteration' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'medium',
    type: 'true_false',
    prompt: 'A simile compares two things using "like" or "as".',
    correct: true,
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the past tense of "bring"?',
    accepted: ['brought'],
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What do we call a word that has the same meaning as another?',
    accepted: ['synonym'],
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'Which word is an adverb in "she sang beautifully at the concert"?',
    options: [
      { id: 'a', text: 'Sang' },
      { id: 'b', text: 'Beautifully' },
      { id: 'c', text: 'Concert' },
      { id: 'd', text: 'She' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'Who wrote the play "Romeo and Juliet"?',
    options: [
      { id: 'a', text: 'Charles Dickens' },
      { id: 'b', text: 'Jane Austen' },
      { id: 'c', text: 'William Shakespeare' },
      { id: 'd', text: 'George Orwell' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'hard',
    type: 'true_false',
    prompt: 'In the sentence "the cake was eaten by the class", the verb is in the passive voice.',
    correct: true,
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What do we call the repetition of the same starting sound in nearby words?',
    accepted: ['alliteration'],
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the collective noun for a group of crows?',
    accepted: ['murder', 'a murder'],
  },
]);
