import { defineBank } from './types.js';

export const generalBank = defineBank('general', [
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'How many days are there in a leap year?',
    options: [
      { id: 'a', text: '364' },
      { id: 'b', text: '365' },
      { id: 'c', text: '366' },
      { id: 'd', text: '367' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Which colour do you get by mixing blue and yellow?',
    options: [
      { id: 'a', text: 'Green' },
      { id: 'b', text: 'Purple' },
      { id: 'c', text: 'Orange' },
      { id: 'd', text: 'Brown' },
    ],
    correctOptionId: 'a',
  },
  {
    difficulty: 'easy',
    type: 'true_false',
    prompt: 'A triangle has three sides.',
    correct: true,
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'How many minutes are there in an hour?',
    accepted: ['60'],
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the young of a cat called?',
    accepted: ['kitten', 'a kitten'],
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'How many players are there in a football (soccer) team on the pitch?',
    options: [
      { id: 'a', text: '9' },
      { id: 'b', text: '10' },
      { id: 'c', text: '11' },
      { id: 'd', text: '12' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Which instrument has 88 keys?',
    options: [
      { id: 'a', text: 'Guitar' },
      { id: 'b', text: 'Piano' },
      { id: 'c', text: 'Violin' },
      { id: 'd', text: 'Flute' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'medium',
    type: 'true_false',
    prompt: 'The Olympic Games are held every four years.',
    correct: true,
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'How many sides does a hexagon have?',
    accepted: ['6'],
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the largest land animal alive today?',
    accepted: ['elephant', 'african elephant', 'the elephant'],
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'How many strings does a standard violin have?',
    options: [
      { id: 'a', text: '4' },
      { id: 'b', text: '5' },
      { id: 'c', text: '6' },
      { id: 'd', text: '7' },
    ],
    correctOptionId: 'a',
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'Which of these is a primary colour of light?',
    options: [
      { id: 'a', text: 'Yellow' },
      { id: 'b', text: 'Green' },
      { id: 'c', text: 'Orange' },
      { id: 'd', text: 'Purple' },
    ],
    correctOptionId: 'b',
    explanation: 'Light mixes from red, green and blue; paint mixes from red, yellow and blue.',
  },
  {
    difficulty: 'hard',
    type: 'true_false',
    prompt: 'A century is one hundred years.',
    correct: true,
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'How many degrees are there in a full turn?',
    accepted: ['360'],
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the currency of Japan?',
    accepted: ['yen', 'japanese yen', 'the yen'],
  },
]);
