import { defineBank } from './types.js';

export const geographyBank = defineBank('geography', [
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Which is the largest ocean on Earth?',
    options: [
      { id: 'a', text: 'Atlantic' },
      { id: 'b', text: 'Indian' },
      { id: 'c', text: 'Pacific' },
      { id: 'd', text: 'Arctic' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'What is the capital city of France?',
    options: [
      { id: 'a', text: 'Lyon' },
      { id: 'b', text: 'Paris' },
      { id: 'c', text: 'Marseille' },
      { id: 'd', text: 'Bordeaux' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'easy',
    type: 'true_false',
    prompt: 'Australia is both a country and a continent.',
    correct: true,
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'How many continents are there on Earth?',
    accepted: ['7'],
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What do we call a very dry region that gets almost no rain?',
    accepted: ['desert', 'a desert'],
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Which mountain range separates Europe from Asia?',
    options: [
      { id: 'a', text: 'The Alps' },
      { id: 'b', text: 'The Andes' },
      { id: 'c', text: 'The Urals' },
      { id: 'd', text: 'The Himalayas' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Which country has the largest population in the world?',
    options: [
      { id: 'a', text: 'China' },
      { id: 'b', text: 'India' },
      { id: 'c', text: 'United States' },
      { id: 'd', text: 'Indonesia' },
    ],
    correctOptionId: 'b',
    explanation: 'India passed China in 2023 and remains the most populous country.',
  },
  {
    difficulty: 'medium',
    type: 'true_false',
    prompt: 'The Equator passes through Brazil.',
    correct: true,
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the longest river in Africa?',
    accepted: ['nile', 'the nile', 'river nile'],
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'Which desert covers most of northern Africa?',
    accepted: ['sahara', 'the sahara'],
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'Which is the deepest point in the world\u2019s oceans?',
    options: [
      { id: 'a', text: 'The Mariana Trench' },
      { id: 'b', text: 'The Puerto Rico Trench' },
      { id: 'c', text: 'The Java Trench' },
      { id: 'd', text: 'The Tonga Trench' },
    ],
    correctOptionId: 'a',
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'What is the capital of Canada?',
    options: [
      { id: 'a', text: 'Toronto' },
      { id: 'b', text: 'Vancouver' },
      { id: 'c', text: 'Montreal' },
      { id: 'd', text: 'Ottawa' },
    ],
    correctOptionId: 'd',
  },
  {
    difficulty: 'hard',
    type: 'true_false',
    prompt: 'Lines of longitude run east to west around the globe.',
    correct: false,
    explanation: 'Longitude runs north to south; latitude runs east to west.',
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'Which country is home to the city of Machu Picchu?',
    accepted: ['peru'],
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the imaginary line at zero degrees latitude called?',
    accepted: ['equator', 'the equator'],
  },
]);
