import { defineBank } from './types.js';

export const historyBank = defineBank('history', [
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Which ancient civilisation built the pyramids at Giza?',
    options: [
      { id: 'a', text: 'The Romans' },
      { id: 'b', text: 'The Egyptians' },
      { id: 'c', text: 'The Greeks' },
      { id: 'd', text: 'The Aztecs' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'What were the large stone castles of medieval Europe mainly built for?',
    options: [
      { id: 'a', text: 'Defence' },
      { id: 'b', text: 'Farming' },
      { id: 'c', text: 'Shipbuilding' },
      { id: 'd', text: 'Mining' },
    ],
    correctOptionId: 'a',
  },
  {
    difficulty: 'easy',
    type: 'true_false',
    prompt: 'The Titanic sank on its first voyage.',
    correct: true,
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What do we call a person who studies the past?',
    accepted: ['historian'],
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What were the earliest widespread cutting tools typically made from?',
    accepted: ['stone', 'flint'],
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'In which year did the Second World War end?',
    options: [
      { id: 'a', text: '1918' },
      { id: 'b', text: '1939' },
      { id: 'c', text: '1945' },
      { id: 'd', text: '1951' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Who was the first person to walk on the Moon?',
    options: [
      { id: 'a', text: 'Buzz Aldrin' },
      { id: 'b', text: 'Yuri Gagarin' },
      { id: 'c', text: 'Michael Collins' },
      { id: 'd', text: 'Neil Armstrong' },
    ],
    correctOptionId: 'd',
  },
  {
    difficulty: 'medium',
    type: 'true_false',
    prompt: 'The Great Wall of China is a single unbroken wall.',
    correct: false,
    explanation: 'It is a network of walls and fortifications built over many dynasties.',
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'Which empire was ruled from the city of Rome?',
    accepted: ['roman empire', 'the roman empire', 'roman'],
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'How many wives did King Henry VIII of England have?',
    accepted: ['6'],
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'The Renaissance began in which country?',
    options: [
      { id: 'a', text: 'France' },
      { id: 'b', text: 'Italy' },
      { id: 'c', text: 'England' },
      { id: 'd', text: 'Spain' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'Which document, sealed in 1215, limited the power of the English king?',
    options: [
      { id: 'a', text: 'The Domesday Book' },
      { id: 'b', text: 'The Bill of Rights' },
      { id: 'c', text: 'Magna Carta' },
      { id: 'd', text: 'The Act of Union' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'hard',
    type: 'true_false',
    prompt: 'The printing press was invented in Europe before paper reached it.',
    correct: false,
    explanation: 'Paper arrived in Europe centuries before Gutenberg\u2019s press of the 1450s.',
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'Which river was central to the civilisation of ancient Egypt?',
    accepted: ['nile', 'the nile', 'river nile'],
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'In which century did the Industrial Revolution begin in Britain? Give the century as a number.',
    accepted: ['18'],
    explanation: 'It began in the 18th century, from around the 1760s.',
  },
]);
