import { defineBank } from './types.js';

export const scienceBank = defineBank('science', [
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'Which planet is known as the Red Planet?',
    options: [
      { id: 'a', text: 'Mars' },
      { id: 'b', text: 'Earth' },
      { id: 'c', text: 'Venus' },
      { id: 'd', text: 'Jupiter' },
    ],
    correctOptionId: 'a',
    explanation: 'Iron oxide dust gives the Martian surface its rusty colour.',
  },
  {
    difficulty: 'easy',
    type: 'multiple_choice',
    prompt: 'What gas do plants take in to make their food?',
    options: [
      { id: 'a', text: 'Oxygen' },
      { id: 'b', text: 'Carbon dioxide' },
      { id: 'c', text: 'Nitrogen' },
      { id: 'd', text: 'Hydrogen' },
    ],
    correctOptionId: 'b',
    explanation: 'Photosynthesis combines carbon dioxide and water using sunlight.',
  },
  {
    difficulty: 'easy',
    type: 'true_false',
    prompt: 'The Sun is a star.',
    correct: true,
  },
  {
    difficulty: 'easy',
    type: 'true_false',
    prompt: 'Spiders are insects.',
    correct: false,
    explanation: 'Spiders are arachnids: eight legs and two body sections, not six and three.',
  },
  {
    difficulty: 'easy',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What force pulls objects towards the centre of the Earth?',
    accepted: ['gravity'],
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'Which part of a plant carries water up from the roots?',
    options: [
      { id: 'a', text: 'Phloem' },
      { id: 'b', text: 'Xylem' },
      { id: 'c', text: 'Stomata' },
      { id: 'd', text: 'Cuticle' },
    ],
    correctOptionId: 'b',
  },
  {
    difficulty: 'medium',
    type: 'multiple_choice',
    prompt: 'What is the chemical symbol for potassium?',
    options: [
      { id: 'a', text: 'P' },
      { id: 'b', text: 'Pt' },
      { id: 'c', text: 'K' },
      { id: 'd', text: 'Po' },
    ],
    correctOptionId: 'c',
    explanation: 'K comes from the Latin name kalium.',
  },
  {
    difficulty: 'medium',
    type: 'true_false',
    prompt: 'Sound travels faster through water than through air.',
    correct: true,
    explanation: 'Water is denser, so its particles pass the vibration along more quickly.',
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the powerhouse of the cell?',
    accepted: ['mitochondria', 'mitochondrion'],
  },
  {
    difficulty: 'medium',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'How many bones are there in an adult human body?',
    accepted: ['206'],
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'Which subatomic particle carries a negative charge?',
    options: [
      { id: 'a', text: 'Proton' },
      { id: 'b', text: 'Neutron' },
      { id: 'c', text: 'Electron' },
      { id: 'd', text: 'Positron' },
    ],
    correctOptionId: 'c',
  },
  {
    difficulty: 'hard',
    type: 'multiple_choice',
    prompt: 'What is the most abundant gas in the Earth\u2019s atmosphere?',
    options: [
      { id: 'a', text: 'Oxygen' },
      { id: 'b', text: 'Nitrogen' },
      { id: 'c', text: 'Carbon dioxide' },
      { id: 'd', text: 'Argon' },
    ],
    correctOptionId: 'b',
    explanation: 'Nitrogen makes up roughly 78 per cent of the air by volume.',
  },
  {
    difficulty: 'hard',
    type: 'true_false',
    prompt: 'Light travels more slowly through glass than through a vacuum.',
    correct: true,
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'text',
    prompt: 'What is the process by which a liquid turns into a gas at its surface?',
    accepted: ['evaporation'],
  },
  {
    difficulty: 'hard',
    type: 'type_answer',
    inputMode: 'number',
    prompt: 'What is the atomic number of carbon?',
    accepted: ['6'],
  },
]);
